apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: a-team-ck
spec:
  id: a-team-ck
  compositionSelector:
    matchLabels:
      cluster: ck
      provider: civo
  parameters:
    nodeSize: small
    minNodeCount: 1
