apiVersion: v1
kind: ConfigMap
metadata:
  name: ksm
data:
  crossplane.yaml: |
    kind: CustomResourceStateMetrics
    metadata:
      name: crossplane
    spec:
      resources:
        - groupVersionKind:
            group: devopstoolkitseries.com
            version: v1alpha1
            kind: SQLClaim
          labelsFromPath:
            name: [metadata, name]
            namespace: [metadata, namespace]
          metrics:
            - name: status_condition
              help: "The conditions of a SQLClaim."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: devopstoolkitseries.com
            version: v1alpha1
            kind: ClusterClaim
          labelsFromPath:
            name: [metadata, name]
            namespace: [metadata, namespace]
          metrics:
            - name: status_condition
              help: "The conditions of a ClusterClaim."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: container.gcp.upbound.io
            version: v1beta1
            kind: Cluster
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a Cluster."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: container.gcp.upbound.io
            version: v1beta1
            kind: NodePool
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a NodePool."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: sql.gcp.upbound.io
            version: v1beta1
            kind: DatabaseInstance
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a DatabaseInstance."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: sql.gcp.upbound.io
            version: v1beta1
            kind: User
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a User."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: postgresql.sql.crossplane.io
            version: v1alpha1
            kind: Database
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a Database."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: kubernetes.crossplane.io
            version: v1alpha1
            kind: Object
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of an Object."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: helm.crossplane.io
            version: v1alpha1
            kind: Release
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a Release."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
