apiVersion: v1
kind: ConfigMap
metadata:
  name: ksm
data:
  crossplane.yaml: |
    kind: CustomResourceStateMetrics
    metadata:
      name: crossplane
    spec:
      resources:
        - groupVersionKind:
            group: devopstoolkitseries.com
            version: v1alpha1
            kind: SQLClaim
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a SQLClaim."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: ec2.aws.upbound.io
            version: v1beta1
            kind: VPC
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a VPC."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: ec2.aws.upbound.io
            version: v1beta1
            kind: Subnet
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a Subnet."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: rds.aws.upbound.io
            version: v1beta1
            kind: SubnetGroup
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a SubnetGroup."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: ec2.aws.upbound.io
            version: v1beta1
            kind: InternetGateway
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a InternetGateway."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: ec2.aws.upbound.io
            version: v1beta1
            kind: RouteTable
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a RouteTable."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: ec2.aws.upbound.io
            version: v1beta1
            kind: Route
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a Route."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: ec2.aws.upbound.io
            version: v1beta1
            kind: MainRouteTableAssociation
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a MainRouteTableAssociation."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: ec2.aws.upbound.io
            version: v1beta1
            kind: RouteTableAssociation
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a RouteTableAssociation."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: ec2.aws.upbound.io
            version: v1beta1
            kind: SecurityGroup
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a SecurityGroup."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: ec2.aws.upbound.io
            version: v1beta1
            kind: SecurityGroupRule
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a SecurityGroupRule."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: rds.aws.upbound.io
            version: v1beta1
            kind: Instance
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a Instance."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: postgresql.sql.crossplane.io
            version: v1alpha1
            kind: Database
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of a Database."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
        - groupVersionKind:
            group: kubernetes.crossplane.io
            version: v1alpha1
            kind: Object
          labelsFromPath:
            name: [metadata, name]
          metrics:
            - name: status_condition
              help: "The conditions of an Object."
              each:
                type: StateSet
                stateSet:
                  labelName: status
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
                  list:
                    - "True"
                    - "False"
                    - "Unknown"
