apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB3lFg5fkT3Bcl2vNSH/3aKDkrRWKrvEbBdC9E/H5Tc5PJGSyyBZG1cYasZfbumRY/S8rEC/hb0nuoAQCpoT0IORPf3hfOhkioy7fKSz+3TMncRpOqEtdV61ZI+CshAIYLPVBydVQynIb75jEnXYaqa0d8VSBgvbFnxGmsrr9IE5jYN2lnfMV0eIzc7l545rbEqzOndvRU8zML5OrFLc9pDgs7hHSIuueQuOpb+TqtkoyM1O4RV+teI1nNgcNhsmYDy4o2busyjxd+Ca/GBARkhVPGukSzmQZ60Tpy/V3cnOqwCdfGOkGqV114hs05byLk5oiF5PI5/oAcDrLjI33+ICWnYqOOXrrveWgKHiy3gRrio02XqyvFWB0drZI+1ijSu9nZImVxCJsL9VSKkIzZK0FFxDq5TuBFCH0zNqlCGzd3zYl1N9LoTG83rXe9P4adjztUbZVYV8o179DvMsgg+SxemnwVVqK8kuvAnSa7+JteOtDhiR1VstUKvsGivw7BYRv8qFrakx0YRdBLlJTkOG7kXtHvpjFU87iCRRSlIE3Q22K8KFUuJ0RBnf3ue8mjUGyIEIvfzx4eZ3Fl4o28mGNpZLwZZic4SzYKgL/9J1ipF0w7+36dZZ9bzbwiQAGpp4ngl6XxlUn2bLxczrYce2YknvbYin6anPn8z7E/owqKq/MxqH9ToJSfULWjhwBRHR5I9PqKOCSK60TR6es6AJupXc8nKywRMVrKyqtdMcbGyhuolz6k+hEsvTRoriRwB6QzIMXF/0UJJ5TK387cPqXQDKP6TLM/3J4tVMBy1052BtUyLv2sal+RSHtwuLzRbqDRHU8M34WQmCxYCz3Ow2iZHlA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

