apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBKCRz1unygT1G96N6fG+EUeme14Y/2SmO15TxxCRNYr5b53SLyhHJkFvPQrFojO/LpXK/Nh2ZVym/2V3pC5DOliPDHhAa61E9ASSOqIwA1jHRW764eQqeSNlWO34+B58fXClQW/78rmFGFJEVDPFpa3d+Nrn0YyjSpWg7upg4kMB1Id95ywQ6yuyqo+0d/CJbVxppVJ5q6UbI139nkn92F3CJ/qsySn+HBV4DozI059TfjYOm0MOvdGK1ZSUkMM0vFPBdWOzXA+sYviGD3VHl5JNgy3MUmy4R7Uh2b9GuwFSQux7MiYzOkbqF/xj53ajkU//+CcuEd3ON8JQYjGUpMaLIjy2+s+2Nh1K+7xa2m5TGKAZrRF/iVf6nXKQ9Sn1P6zCUYLLerozmuHkflPeO2Lcp0tSA9fS9FUkyJsjY9RpJpL/9Nk5qZr7S9kdF3rR7BlC7NgzgOQqVje49xizfA/fX1K0vGrw/qkbCg9VNIxTrOcGKqIwNa5WTRjNZEHC3HN1XYO5GgmnKlPT5ZlPNk9/bcMYpMIu2SSWFqxbgxbJdlHdzY8aD/Gk0UjNJMjYHqMqEnAoURaSbHcwjevS48/E7ccUwFZiA73+ebkJ6uUQGVc0GVLrMOWs9RNsK9PmvE5KLyoS21gr7ozN8GqB3OmH7Lcq3Nwf2PXPf9538Ooa82b8IPU/jGq3rZXIlnpaoVPkQnf0KAyuY32zKCDxNHHWMri3hCNKonCn507Fj+ouppByh+CsEZh+i0aBtth82ENPqDlhgeQgy5S4sfj1qaeRjCA3aKKCcNK6XjtuP4pjSI1mU9lehXLGrxkGvAAk7AjUlMtaMamk6+U4HAlMYTd7kLgQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

