apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBsCE1eC4qEkmYtU8buOwH3wALeOEvaSW/8emh0PmZdc+Rx+RvLa1nRmIFULG/BNNgJMcR8YKIQvZfYQNezZZIvSvdqmysUz9mHNFYO4WEcm07THB6CVFp+DX8fVtrA1ByGhTVWjkyTJfCGLksDodNEXISFtrS4REHIqT9kCPqQZan4fp4BnuclYrgfknvBZkB6txyqvZV36WhxZU40U6A0YkpNvuK49E8m/2NI6KiDn9aVvK+yRhMJLIiW02lSVAfsN1T2DCVWoK3li5JPfbK8ThpMlFxlmGe8A1bCJ/TSZGqZABDCgahwEKo+sS1LT1wFUbtauqoblH4jRcEXKRCAkM7ewxuodoKjxB7v/2q81/Va0bHV0nZerajdXbfDhW+H+J9xVTp6v+lJ1NNdS9YN7aC2KL/TzYV9yusNDi27vvnOZjmOrxz5jM+atmdrNC5d/8jIXCFfyKyN3W/qSMt5jVR14rBATrnMlXuGgThHgccjra2HMHDygDTlIcaECSkJNo7Zm3MiAbTwQ0Em2F99ePPK7XMFT/Izq9/gc0N235YLd+OpakmNPvJLIW70hbTwmaH81yJQAnI8pJOENUawjaLATcya/Z73KN9D6tbdCKoGputy5QZwD/T2iyAZOpY6OUA4xRNgf5giZiQMNHb8h36PT3X3S4JlAMPFC5anpiBN50rNezy6Nc4tHJdFg73FD4ls/T7vYqCLS2bqfxI3KvtrJrIW1tkHQoit1oLmXG/+qc9pSAg5K2JYDfAiFZkmWxTvFD+xb/K6AWUhYSd1D2e3G4rCfvrgS9CMs8qXGQfNTlBIX9VB1p+0EkkslSWVBlaO32XMFauD/rm1qx+XxFlmjA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

