apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgDO/pA1hbERbILtvk9dipIskhbeEndQmhhXSKVNFvFC98ocEbGaKbZHWjDSQqu5VsxkUWf2sRH9KwpKcE8vrka99GY4tivHR8lqKJP+FVtSb6TiKOfGF6vv8NSHXsPYy/Fu3H8AtZsjwOcbADhW5R+BwScVE3nNJNEIPCShszYqKDpjqA0cywaH7fko9dW6sUSvtsKPkLK7ARpyatBlZ+NABWmBmNlXp3wB7lyJ9CiqPopJGbDIlyKXEUEGZA8Vc4cTZBGqCymP3jUzO/dR5yByEUg5LJsW4F8aGxPPeGChs24H0HhWTYfSe5miTVEZVdbZ7aieKa1DAB2oQUgSftJnwI77lHWV/6U1VatlMnOenGluRydzN7GSHfMvN8iVTCzt+X+9h/aQUvssInmSo8CQZ18o4Vr//Vqo759r18gImPeSehRZNAbrPAiEhF+LAWaLRjDM7UjP/gXNmWw2BRscPPP8XiynRW1k5UoUO+83XT2TLx699L6bDuBZwdVecKmStvoglBF9+CJjtMw5oZNxZTlshWbLi3JWpkcBaiMS4rsI9C4DM4yxiUDJZkwOzTgGxza17+ZJtdOoWRhwQLPbcafhXaimYcBCVmIAWZ5J7hiJcaGTKnQXbcUd/tFE239MmBSL+CZa4JuPcgPUWniiig0PWxl+kqN6rE7lRzpMm6WTSGmdSUYvl5ixt8u+j/9aFyTjUDvpRMXuQ3H/3osC8GvKeTcvAoasNiO023HjbasD/lFwxJTTk+eeiuQW1EL9YSK75Fc+UZ7tcP4YA64eNQV4YC3+USlutfPGwVq1a6PSB+ztwpnRqcfBn++keOmCGI4E5SIe6EN8+u8QoIGCGHa83Mg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

