apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBVj6mksVQm8ApW7Ab5QRbUN0q6JfbLpGmhAPDQrgpCkHzg3JZN50gmrV2V9QAd6pHYj1l9JpQ0RATsAeUXmAbcREK/qXCtK1j+meX8bBe3UVEvyYY3qqoHMc+Oz9J7/FgwlSAddKFqhiYRhlxIb7QDy1iPlpI7vn206opBbAQTUaTDZrpTB86fW9mz+Fd7ijj34ZxWnUUyVQHgjMhMVwYFXtbukT36jjPaRBWmhyZIckaD6M/ynPy6+l8N4U8tfvgRuKLkq81kOGuYUO1VYSN201fcPLt2poCtDLYvo1q1/45GGUtIzdBmT3i+BEpdWauCh95gPhK+TtwkvnXoqOSfShaLRhA5moENtsI9pia7QMXq0nRUqaQmAIsFTTeBJN6n7PH8WmWfnHxAguU9HT7GiKgNJGibSIQwh6qRBPqTPecs+KYKTLPK4vGuIMpmlXkmKbGXub1m8ybnMaZsr2Lq+Xw0xEP/ipof/9UKynOnMTC8FD6cKbLRVZy2kB7lULyLx2N7R1csp8IC50FgQbkAHwTCwcLchsbKSPST1ZQlvNxalOQF0a54/UXIsG4raT2uDfGUZMXZ7dT6lK64lmlzt+V19bMKqDRZcoZn37V1ryteXpyDRkKqEzzdFNr3TF9hGJryw8Dk3of9AKqqfUWYwU2yOeE84EfIs8qLY6mt3+oWoJ2WziP/jIR39qNOAPR5fA4KfESsVKecTKL5Ums6I1QMvqOTZUeMKUEhFuA014SK6nHpk/5cB7V0ULkSZGz6M9BAymAuPB6N4gjM3zIQIsV2ZPs1+0dmuaTJTy5xtIPZRXpLsuANWAiExl7gBkpPsgucvMk5wyv5PtblNzpCO8Ed8A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

