apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBPAWScvk+7XpE6d/pCCHoGl95QjtNLboODn7NquA1oYiOoEqFCJ86t6xLjYvC/0iBQkZ4xzUHNV/7xcsCH58KSomTF8OMMO7gjJwPFGhXs7WyKOvATEnT+BT2tgTzt58w8PZRdEh2Q8GzSYi2dj+ghzgSlfZPLg+eQXItm4RVMQHEHHVbwPFtZI5l1azfWk5AIejDMde18TErS1LC02hUkZAZisbfN3lG4sPpcRLawigL31YgJ/ZSwTxyN2I8BItLZn+yQjEYdVOCyt1PEs2I6gmgjlhI+X9DUNyHIa2dgt+1eFF7lYXeu/pINAyZNjiVbiqze0IbIy+kB9lC4q2ZpIHZqF+x6+x0fzTp2GsuqUfHjoCWQyn1Mz8hxfRjLvD0+xoKseqN2Zs0kU+58KypBcOjaMn//Nts+xT5NRVZnHEeeK2AZOhDezuVrPNfFReOpJPPKjP4Pt1Kf+itPOWJ4/QUCSvIL4xHsKkf2fhUZy9oEmlUFCHPYSBcwi5lH5GWUhB7G2q44dihadBp2ipFTX1Ai7bJHb54HHfk4bYYqq8fFTaShdgpjwzalKuxJ1LwiwWl0JkbQiXO5+R7CLejtlPErAMJSho4cJlxI1ADtDunvXxxxSKfwQRRw2CKjmsXRqwsIZOUmdUD/yQs9GqNlB/3LkSMVXR34o7sUgI3RUDoyrVc/+ztlgUyApw8E9OnpgxOxDEt2r/Al/TmbnO5Yg00qCAAlO4BOb+FAvDU8lcDdku2L6Y4xv0vJkMk8yrY/e43r8GQ2Qa5i4eQEnzALW73N1V8wiXIeziQFf4hKI9/JbQVZEBLjKOZ/WiibF+4PWv7blCXAtzhmv4EInqlkLi811Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

