apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAm5tbbcUdIGy69KIHj4dztNu2Kcq54u4OM0yLbtM8W1A+J/TcDfbPfiw+OnLr/daOsEV45sVQLfYRxcwRRZfOos92DUcvc1uruGkYB2rnJnJd9lORFveA+H4fE0e4CK7SXjThiVjgLwephj/00yq4yL7K3Stz6WXRfn2hI3F440suHRd+tDW4ykCuKZWiwdxX9Xo1Z8I0vziKkbuxHnpaJsWXKyVMZAE/9XoaetmA146w1lOkZKOyHbWx2uxk9KmhifkpTurUL97OBsIimqvc5JsIAWjnTGHldkNxE4fG0xAuKPbmc31zR1Y5RNXyfUnyleXjRLUcEvEkRBuNWXIHxMmPgtK7yZmuUdQ7iIk3Sy8VwTp9rzrlU6GeETXrQJKG0XPjbiHP1I7DmWfPP4wywqIiw0jXffbOJ4FKC1TDs2qZOVcGmydIFZ6Qr3KK2f9j7Rje6K9ylsaEm1gn54ALZTUPYfth6Ecutp5YvvROh630l3s7xWQYXn67hd7fT9P3a6v1pQCc/FlgU73+j0AqtUiRYoCmP0dkNQAqv0ctiOsKqt9uOdMDGHlufIr6Smz/Od6grxCVvsHmLCeYO7BNqaR3wjSPB54nOYK5RaUSVN8X64cQD42zEj7ZK6vEy1PO6pUO6y+THxFYs4JD6K18hQ2II79ZwsANixT4cCKKys78GxrtU6oOA7v74nN7btEkMn7PlSgrRfK7OEE2jC98fVtYia9raCEQLarJbrNN7usH+d8YEp3RpyiBfyKs5ksFecpQ1LOOnpQcwGOIU+E/Sahl74OYZbqXeeP2aax9iuiA7O8GREwjZBu5mEsPzr8KhN0YlFp+9k8mIjMXMH15Zx0uzgw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

